# https://doc.rust-lang.org/rustc/profile-guided-optimization.html
# https://nikolaivazquez.com/blog/divan/#measure-allocations
# https://doc.rust-lang.org/cargo/reference/profiles.html

[workspace]
resolver = "2"

members = [
    "crates/bvh",
    "crates/lunar",
    "crates/server",
    "crates/persist",
    "crates/proxy",
    "crates/protocol",
    "events/infection",
    "examples",
]

[profile.release-full]
inherits = "release"
debug = false
lto = "fat"
codegen-units = 1
panic = "abort"


# custom release-debug profile
[profile.release-debug]
inherits = "release"
debug = true

[profile.bench]
#debug = true
lto = "fat"
codegen-units = 1

[workspace.dependencies]

bvh-region = { path = "crates/bvh" }
glam = "0.26.0"
hyperion = { path = "crates/server" }
hyperion-proxy = { path = "crates/proxy" }
hyperion-proto = { path = "crates/protocol" }

# todo: re-enable rayon
#evenio = { git = "https://github.com/andrewgazelka/evenio", features = ["rayon"], branch = "feat-sender-state-public"}

