version: '3.8'
services:
  hyperion-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: hyperion-proxy-debug
    ports:
      - "25565:25565"
    command: ["--server", "proof-of-concept:35565", "0.0.0.0:25565"]  # Fixed argument order and format
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    networks:
      - proxy-network
    depends_on:
      - proof-of-concept

  proof-of-concept:
    build:
      context: .
      dockerfile: Dockerfile
      target: proof-of-concept-debug
    expose:
      - "35565"
    command: [ ] # ["--ip", "0.0.0.0", "--port", "35565"]
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    networks:
      - proxy-network

  hyperion-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: hyperion-bot-debug
    command: [ ] # ["--ip", "0.0.0.0", "--port", "35565"]
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - HOST=hyperion-proxy:25565
      - MAX_NUMBER_OF_BOTS=10
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
