[package]
name = "hyperion"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
anyhow.workspace = true
tracing = { workspace = true }
serde_json.workspace = true
bytes.workspace = true

valence_text.workspace = true
valence_protocol.workspace = true
valence_registry.workspace = true
valence_anvil.workspace = true
valence_server.workspace = true
valence_nbt.workspace = true
valence_generated.workspace = true

hyperion-utils.workspace = true

#chunk.workspace = true

# no secure alloc
sha2.workspace = true
itertools.workspace = true
base64.workspace = true
bitfield-struct.workspace = true
bitvec.workspace = true
bumpalo.workspace = true
bvh-region.workspace = true
bytemuck.workspace = true
byteorder.workspace = true
derive_more.workspace = true
dirs-next.workspace = true
enumset.workspace = true
fastrand.workspace = true
flate2 = { workspace = true, features = ["zlib-ng"] }
flecs_ecs.workspace = true
fxhash.workspace = true
glam = { workspace = true, features = ["serde"] }
heapless.workspace = true
heed.workspace = true
hyperion-crafting.workspace = true
hyperion-inventory.workspace = true
hyperion-palette.workspace = true
hyperion-proto.workspace = true
hyperion-text.workspace = true
indexmap.workspace = true
kanal.workspace = true
libc.workspace = true
libdeflater.workspace = true
memmap2.workspace = true
more-asserts.workspace = true
ndarray.workspace = true
no_denormals.workspace = true
once_cell.workspace = true
ouroboros.workspace = true
parking_lot.workspace = true
prost.workspace = true
rayon.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
roaring = { workspace = true, features = ["simd"] }
serde = { workspace = true, features = ["derive"] }
tar.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
toml.workspace = true
uuid = { workspace = true, features = ["v3"] }

[dev-dependencies]
divan.workspace = true
fastrand.workspace = true
hex.workspace = true
rustc_version.workspace = true
tango-bench.workspace = true
tracing-subscriber.workspace = true

[[bench]]
name = "set"
harness = false

[[bench]]
name = "atomic"
harness = false

[lints]
workspace = true

[build-dependencies]
rustc_version.workspace = true
