[dependencies]
flecs_ecs.workspace = true

[lints]
workspace = true

[package]
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
edition = "2021"
name = "hyperion-utils"
publish = false
readme = "README.md"
version = "0.1.0"
