[package]
name = "hyperion-proto"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
prost.workspace = true

[lints]
workspace = true

[build-dependencies]
prost-build.workspace = true

[package.metadata.cargo-machete]
ignored = ["prost"]
