[package]
name = "lunar-proto"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
prost.workspace = true
prost-types.workspace = true

[build-dependencies]
prost-build.workspace = true

[lints]
workspace = true
