[package]
name = "infection"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
anyhow.workspace = true
hyperion.workspace = true
flecs_ecs.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["chrono", "env-filter"] }
clap = { workspace = true, features = ["derive"] }
tracing-tracy.workspace = true
dotenvy = "0.15.7"
nom = "7.1.3"

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["release_max_level_info"] }

[lints.clippy]
complexity = "deny"

nursery = { level = "deny", priority = -1 }

pedantic = { level = "deny", priority = -1 }
missing_errors_doc = "allow"

perf = "deny"
style = "deny"
suspicious = "deny"
