[package]
name = "hyperion-proxy"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
anyhow = "1.0.86"
prost = "0.12.6"
tokio = { version = "1.37.0", features = ["full"] }
bvh = { git = "https://github.com/andrewgazelka/bvh-data" }
glam = "0.26.0"
arc-swap = "1.7.1"
slotmap = "1.0.7"
tracing = "0.1.40"
bytes = "1.6.0"
tracing-subscriber = "0.3.18"
hyperion-proto.workspace = true
heapless = "0.8.0"

[lints.clippy]
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }

redundant_pub_crate = "allow"
future_not_send = "allow"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_precision_loss = "allow"
missing_errors_doc = "allow"
module_name_repetitions = "allow"
missing_panics_doc = "allow"
module_inception = "allow"
