[package]
name = "hyperion-palette"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
anyhow.workspace = true
valence_protocol.workspace = true

[lints]
workspace = true
