[package]
name = "hyperion-event-macros"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]
readme = "README.md"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = "2.0.79"
convert_case = "0.6.0"
proc-macro2 = "1.0.88"

[dev-dependencies]
trybuild = "1.0.100"
hyperion.workspace = true

[lints]
workspace = true
